version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: '20:00'
  open-pull-requests-limit: 10
  target-branch: "dev"
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: '20:00'
  open-pull-requests-limit: 10
  target-branch: "dev"
