name: Check pull request target branch
on:
  pull_request_target:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  check-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Check branches
        run: |
          if [ ${{ github.base_ref }} == "dev" ]; then
            echo "Pull requests are only allowed to dev branch."
            exit 1
          fi
