name: release
on:
  push:
    tags:
      - "*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "0.125"
          extended: true

      - uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: install deps
        run: npm ci

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

  merge:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.AGENCY_RELEASER_ID }}
          private-key: ${{ secrets.AGENCY_RELEASER_KEY }}
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ steps.generate_token.outputs.token }}
      - name: merge
        run: |
          git fetch --tags origin
          git merge $GITHUB_REF
          git push origin master
