name: test
on: push
jobs:

  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: install deps
        run: npm ci
      - name: run check
        run: npm run licenses:check

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: install deps
        run: npm ci

      - name: Build
        run: hugo --minify
